// <auto-generated />
namespace MvcOnlineTicariOtomasyon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class kargodetayy_table_create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kargodetayy_table_create));
        
        string IMigrationMetadata.Id
        {
            get { return "202307131902336_kargodetayy_table_create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
